"""add job_class to user

Revision ID: 03cfe6f15b11
Revises: bd4ba44f02a7
Create Date: 2026-01-18 23:07:13.874015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cfe6f15b11'
down_revision: Union[str, Sequence[str], None] = 'bd4ba44f02a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.CHAR(length=32),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('completion_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_logs_user_id'))

    with op.batch_alter_table('conversation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('daily_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_outcomes_user_id'))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))

    with op.batch_alter_table('habit_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_states_user_id'))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(100)'))
        batch_op.alter_column('is_purchasable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    with op.batch_alter_table('lore_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lore_progress_user_id'))

    with op.batch_alter_table('push_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_profiles_user_id'))

    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quests_goal_id'))
        batch_op.drop_index(batch_op.f('ix_quests_user_id'))

    with op.batch_alter_table('rivals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rivals_user_id'))

    with op.batch_alter_table('user_talents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_talents_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.alter_column('penalty_pending',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('streak_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('streak_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('penalty_pending',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))
        batch_op.drop_column('settings')
        batch_op.drop_column('job_class')

    with op.batch_alter_table('user_talents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_talents_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('rivals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rivals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quests_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quests_goal_id'), ['goal_id'], unique=False)

    with op.batch_alter_table('push_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_profiles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('lore_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lore_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('is_purchasable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(100)'))

    with op.batch_alter_table('habit_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_states_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('daily_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_outcomes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('conversation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_logs_id'))

    with op.batch_alter_table('completion_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
