"""Add UserPIDState for behavioral engineering

Revision ID: ecdbcc528ad9
Revises: 03cfe6f15b11
Create Date: 2026-01-20 16:31:33.844178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdbcc528ad9'
down_revision: Union[str, Sequence[str], None] = '03cfe6f15b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pid_states',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('integral', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Float(), nullable=True),
    sa.Column('error_history', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('user_pid_states')
    # ### end Alembic commands ###
